# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fe6bc2edadde7d3819b887a499f223f1"
name = "wishlist app"
handle = "wishlist-app-366"
application_url = "https://kb-silicon-normal-touched.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://kb-silicon-normal-touched.trycloudflare.com/auth/callback",
  "https://kb-silicon-normal-touched.trycloudflare.com/auth/shopify/callback",
  "https://kb-silicon-normal-touched.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
